# Generated by Django 3.0.7 on 2020-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='00000', max_length=12)),
                ('email', models.EmailField(default='test@maclo.com', max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('job_profile', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='')),
                ('relationship_status', models.CharField(choices=[('Single', 'Single'), ('Commited', 'Commited'), ('Divorcee', 'Divorcee'), ('Married', 'Married'), ('Widow', 'Widow'), ('Engaged', 'Engaged'), ('Other', 'Other')], default='Single', max_length=100)),
                ('your_interests', models.CharField(default='reading books', max_length=500)),
                ('fav_quote', models.CharField(default='MY Fav QUOTE', max_length=1000)),
                ('living_in', models.CharField(choices=[('Noida', 'Noida'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Gurgaon', 'Gurgaon'), ('Chennai', 'Chennai'), ('Kerala', 'Kerala'), ('Gujrat', 'Gujrat'), ('Ahmedabad', 'Ahmedabad')], default='Delhi', max_length=100)),
                ('profession', models.CharField(choices=[('IT Support', 'IT Support'), ('Software Developer', 'Software Developer'), ('Model', 'Model'), ('Director', 'Director'), ('Fitness Trainer', 'Fitness Trainer'), ('Doctor', 'Doctor'), ('Actor', 'Actor'), ('Nutritionist', 'Nutritionist'), ('Human Resource', 'Human Resource')], default='Model', max_length=100)),
                ('qualification', models.CharField(choices=[('Matriculate', 'Matriculate'), ('Intermediate', 'Intermediate'), ("Bachelor's", "Bachelor's"), ("Matser's", "Matser's"), ('Doctrate', 'Doctrate')], default="Bachelor's", max_length=100)),
                ('college_name', models.CharField(choices=[('IIT', 'IIT'), ('IIIT', 'IIT'), ('NIT', 'NIT'), ('IISC', 'IISC'), ('BITS PILANI', 'BITS PILANI'), ('AIIMS', 'AIIMS'), ('IIM', 'IIM')], default='IIT', max_length=100)),
                ('university', models.CharField(choices=[('DU', 'DU'), ('JNU', 'JNU'), ('BHU', 'BHU'), ('CCSU', 'CCSU'), ('IPU', 'IPU'), ('AKTU', 'AKTU')], default='DU', max_length=200)),
                ('personality', models.CharField(default=None, max_length=500)),
                ('interest', models.CharField(default=None, max_length=500)),
                ('preference_first_date', models.CharField(choices=[('Tea', 'Tea'), ('Coffee', 'Coffee'), ('Soft Drinks', 'Soft Drinks'), ('Beer', 'Beer'), ('Wine', 'Wine'), ('Whisky', 'Whisky')], default='Tea', max_length=150)),
                ('fav_music', models.CharField(default=None, max_length=500)),
                ('travelled_place', models.CharField(default=None, max_length=500)),
                ('once_in_life', models.CharField(default=None, max_length=500)),
                ('exercise', models.BooleanField(default=False)),
                ('looking_for', models.CharField(default='relationship', max_length=500)),
                ('fav_food', models.CharField(default=None, max_length=500)),
                ('fav_pet', models.CharField(default=None, max_length=100)),
                ('smoke', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('religion', models.CharField(default='atheist', max_length=100)),
                ('body_type', models.CharField(default='slim', max_length=100)),
                ('pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_9', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInstagramPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_9', models.ImageField(blank=True, null=True, upload_to='')),
                ('insta_pic_10', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
