# Generated by Django 3.0.7 on 2020-07-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
    ]
