# Generated by Django 3.0.7 on 2020-07-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_userdetail_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='first_name',
            field=models.CharField(default='maclo', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(default='app', max_length=100),
        ),
    ]
