# Generated by Django 3.0.7 on 2020-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200701_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@maclo.com', max_length=254)),
                ('first_name', models.CharField(default='maclo', max_length=100)),
                ('last_name', models.CharField(default='app', max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('job_profile', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(choices=[('Matriculate', 'Matriculate'), ('Intermediate', 'Intermediate'), ("Bachelor's", "Bachelor's"), ("Matser's", "Matser's"), ('Doctrate', 'Doctrate')], default="Bachelor's", max_length=100)),
                ('relationship_status', models.CharField(choices=[('Single', 'Single'), ('Commited', 'Commited'), ('Divorcee', 'Divorcee'), ('Married', 'Married'), ('Widow', 'Widow'), ('Engaged', 'Engaged'), ('Other', 'Other')], default='Single', max_length=100)),
                ('your_interests', models.CharField(default='reading books', max_length=500)),
                ('fav_quote', models.CharField(default='MY Fav QUOTE', max_length=1000)),
                ('pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_9', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='fav_quote',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='images',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='job_profile',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_1',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_2',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_3',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_4',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_5',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_6',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_7',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_8',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic_9',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='relationship_status',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='your_interests',
        ),
    ]
