# Generated by Django 3.0.7 on 2020-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200701_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='phone_number',
            field=models.CharField(default='00000', max_length=12),
        ),
    ]
