# Generated by Django 3.0.7 on 2020-07-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20200701_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.RegisterUser'),
        ),
    ]
