# Generated by Django 3.0.7 on 2020-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_userdetail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(default='sdjhkfsjh', max_length=600),
        ),
    ]
