# Generated by Django 3.0.7 on 2020-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_userdetail_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='drink',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='exercise',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='smoke',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
