# Generated by Django 3.0.7 on 2020-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200701_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='drink',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='exercise',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='smoke',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='No', max_length=10),
        ),
    ]
