# Generated by Django 3.0.7 on 2020-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20200701_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='liked_by',
            field=models.ManyToManyField(default=1, related_name='liked_by', to='src.RegisterUser'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='superliked_by',
            field=models.ManyToManyField(default=1, related_name='superliked_by', to='src.RegisterUser'),
        ),
    ]
