# Generated by Django 3.0.7 on 2020-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20200701_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='superliked_by',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='liked_by',
            field=models.ManyToManyField(default=1, related_name='_registeruser_liked_by_+', to='src.RegisterUser'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='superliked_by',
            field=models.ManyToManyField(default=1, related_name='_registeruser_superliked_by_+', to='src.RegisterUser'),
        ),
    ]
