# Generated by Django 3.0.7 on 2020-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20200701_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='your_interests',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='interests',
            field=models.CharField(default='Reading Books', max_length=500),
        ),
    ]
