# Generated by Django 3.0.7 on 2020-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20200701_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='religion',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='body_type',
            field=models.CharField(default='slim', max_length=100),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='religion',
            field=models.CharField(default='atheist', max_length=100),
        ),
    ]
