# Generated by Django 3.0.7 on 2020-07-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20200701_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Noida', 'Noida'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Gurgaon', 'Gurgaon'), ('Chennai', 'Chennai'), ('Kerala', 'Kerala'), ('Gujrat', 'Gujrat'), ('Ahmedabad', 'Ahmedabad')], default='Delhi', max_length=100)),
                ('max_distance', models.IntegerField(default=10)),
                ('age_range', models.IntegerField(default='18')),
                ('show_me_on_app', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], max_length=100)),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.RegisterUser')),
            ],
        ),
    ]
