# Generated by Django 3.0.7 on 2020-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20200701_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='liked_by_me',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='super_liked_by_me',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='superliked_by',
        ),
        migrations.CreateModel(
            name='MatchedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ManyToManyField(default=1, related_name='liked_by', to='src.RegisterUser')),
                ('liked_by_me', models.ManyToManyField(default=1, related_name='liked_by_me', to='src.RegisterUser')),
                ('super_liked_by_me', models.ManyToManyField(default=1, related_name='superliked_by_me', to='src.RegisterUser')),
                ('superliked_by', models.ManyToManyField(default=1, related_name='superliked_by', to='src.RegisterUser')),
            ],
        ),
    ]
