# Generated by Django 3.0.7 on 2020-07-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20200701_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matcheduser',
            old_name='superliked_by',
            new_name='super_liked_by',
        ),
    ]
