# Generated by Django 3.0.7 on 2020-07-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20200701_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.RegisterUser')),
            ],
        ),
    ]
