# Generated by Django 3.0.7 on 2020-07-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_requestmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom')], default='Male', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('venue', models.TextField()),
                ('description', models.TextField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.RegisterUser')),
            ],
        ),
    ]
