# Generated by Django 3.0.7 on 2020-07-02 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_auto_20200702_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 2, 7, 13, 41, 771244, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 2, 7, 13, 55, 53090, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulemeeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 2, 7, 14, 3, 531961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
