# Generated by Django 3.0.7 on 2020-07-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_aboutus_contactus_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=models.TextField(),
        ),
    ]
