# Generated by Django 3.0.7 on 2020-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_auto_20200702_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.BigIntegerField(default='+9199999', max_length=13),
        ),
    ]
