# Generated by Django 3.0.7 on 2020-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_auto_20200702_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='fb_signup',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='insta_connect',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='verified',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.BigIntegerField(default='+9199999'),
        ),
    ]
