# Generated by Django 3.0.7 on 2020-07-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_auto_20200702_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_name', models.CharField(default='From User', max_length=250)),
                ('to_user_name', models.CharField(default='To user name', max_length=200)),
                ('notification_type', models.CharField(default='Notification type', max_length=200)),
                ('notification_title', models.CharField(default='Notification Title', max_length=200)),
                ('notification_body', models.TextField()),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='src.UserDetail')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='src.UserDetail')),
            ],
        ),
    ]
