# Generated by Django 3.0.7 on 2020-07-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstagrampic',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='userinstagrampic',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
