# Generated by Django 3.0.7 on 2020-07-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_auto_20200703_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstagrampic',
            name='phone_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.RegisterUser'),
        ),
    ]
