# Generated by Django 3.0.7 on 2020-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_userinstagrampic_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom')], default='Male', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='job_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Matriculate', 'Matriculate'), ('Intermediate', 'Intermediate'), ("Bachelor's", "Bachelor's"), ("Matser's", "Matser's"), ('Doctrate', 'Doctrate')], default="Bachelor's", max_length=100, null=True),
        ),
    ]
