# Generated by Django 3.0.7 on 2020-07-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_auto_20200703_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Commited', 'Commited'), ('Divorcee', 'Divorcee'), ('Married', 'Married'), ('Widow', 'Widow'), ('Engaged', 'Engaged'), ('Other', 'Other')], default='Single', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='religion',
            field=models.CharField(blank=True, default='atheist', max_length=100, null=True),
        ),
    ]
